### ISSUE TITLE
missing meqtrees dependency 

### ISSUE THREAD

**Issue by TariqBlecher** [radio-astro/packaging#10]
So I'm running turbo-sim using mqt.run and there appears to be missing a casa library.
### Starting meqserver

/usr/bin/meqserver: error while loading shared libraries: libcasa_synthesis.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/meqtree-pipeliner.py", line 73, in <module>
    mqs = meqserver.default_mqs(wait_init=10,extra=["-mt",str(options.mt)]);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/meqserver.py", line 262, in default_mqs
    mqs = meqserver(extra=extra,**args);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/meqserver.py", line 94, in **init**
    multiapp_proxy.**init**(self,appid,client_id,spawn=spawn,**kwargs);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/multiapp_proxy.py", line 211, in **init**
    self.ensure_connection(wait_init);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/multiapp_proxy.py", line 438, in ensure_connection
    raise RuntimeError,"timeout waiting for connection";
RuntimeError: timeout waiting for connection

**Comment by gijzelaerr** [comment]
try installing casarest

**Comment by TariqBlecher** [comment]
Now it returns:

### Starting meqserver

/usr/bin/meqserver: error while loading shared libraries: libboost_thread.so.1.54.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/meqtree-pipeliner.py", line 73, in <module>
    mqs = meqserver.default_mqs(wait_init=10,extra=["-mt",str(options.mt)]);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/meqserver.py", line 262, in default_mqs
    mqs = meqserver(extra=extra,**args);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/meqserver.py", line 94, in **init**
    multiapp_proxy.**init**(self,appid,client_id,spawn=spawn,**kwargs);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/multiapp_proxy.py", line 211, in **init**
    self.ensure_connection(wait_init);
  File "/usr/lib/python2.7/dist-packages/Timba/Apps/multiapp_proxy.py", line 438, in ensure_connection
    raise RuntimeError,"timeout waiting for connection";
RuntimeError: timeout waiting for connection

**Comment by gijzelaerr** [comment]
You are trusty right
Op 3 sep. 2015 2:34 PM schreef "Tariq Blecher" notifications@github.com:

**Comment by TariqBlecher** [comment]
yes

**Comment by TariqBlecher** [comment]
ok installed it

**Comment by gijzelaerr** [comment]
What did you install? How where you able to install meqtrees without installing casarest? how where you able to install casarest without boost?

you where using the packages right?

**Comment by gijzelaerr** [comment]
@TariqBlecher

**Comment by TariqBlecher** [comment]
Yes I used packages but I also was messing around with the installations before
the dependencies bug was fixed.

**Comment by TariqBlecher** [comment]
Oh I installed the default libboost multithreaded in my apt-cache
